Neos:
  MetaData:
    ContentRepositoryAdapter:
      mapping:
        defaultEelContext:
          String: 'TYPO3\Eel\Helper\StringHelper'
          Array: 'TYPO3\Eel\Helper\ArrayHelper'
          Date: 'TYPO3\Eel\Helper\DateHelper'